[WM-2051] Update number of accepted inputs from 100 to 160
DataBiosphere/cbas pull request #173
Opened 2023-06-20 15:23 UTC by kpierre13

2023-06-23 16:15 UTC, mspector approved these changes

2023-06-23 16:15 UTC, mspector commented
approved with the knowledge that the Pact failure is unrelated

2023-06-23 16:20 UTC, salonishah11 requested changes

2023-06-23 16:20 UTC, salonishah11 commented on service/src/main/resources/application.yml
> +    maxWorkflowOutputs: 300
I think it would be good to add unit tests related to this change

2023-06-27 15:47 UTC, salonishah11 approved these changes

2023-06-27 17:57 UTC, merged