[WM-2254] Workflow completion callback hitting run not found exception
DataBiosphere/cbas pull request #209
Opened 2023-09-28 01:44 UTC by zykonda

1. Added implementation of getting Run record by the runId (WorkflowId) and updated controller code to use it.
2. TestRunDao renamed to TestRunsFilters according to the test logic.
3. TestRunDao validates a new method with a call to db. Both TestRunDao and TestRunSetDao are manual tests requiring an explicit db cleanup after. Something to re-think later for a validation strategy.

2023-09-28 19:47 UTC, kpierre13 approved these changes

2023-09-29 15:00 UTC, cjllanwarne requested changes
I like the test changes but I think there's an easier way to implement the new run_id (and engine_id) search filters

2023-09-29 15:54 UTC, zykonda commented on service/src/main/java/bio/terra/cbas/dao/RunDao.java
> +  public Optional<Run> getRunByIdIfExists(UUID runId) {
I understand the intention, but how the RunsFilters(uuid, ...) signature would be different for engineId (or runId) if uuid is a shared type with runSetId?

2023-09-29 19:56 UTC, cjllanwarne approved these changes

2023-09-30 00:59 UTC, merged